kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: quay
spec:
  to:
    kind: Service
    name: quay-app
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
