apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    quay-component: clair
  name: clair
spec:
  replicas: 1
  selector:
    matchLabels:
      quay-component: clair
  template:
    metadata:
      labels:
        quay-component: clair
    spec:
      containers:
        - image: quay.io/projectquay/clair
          imagePullPolicy: IfNotPresent
          name: clair
          env:
            - name: CLAIR_CONF
              value: /clair/config.yaml
            - name: CLAIR_MODE
              value: combo
          ports:
            - containerPort: 8080
              name: clair-http
              protocol: TCP
            - containerPort: 8089
              name: clair-intro
              protocol: TCP
          volumeMounts:
            - mountPath: /clair/
              name: config
            - mountPath: /var/run/certs
              name: certs
          # TODO(alecmerdler): Define `readinessProbe` which waits until indexer/matcher services are ready.
      restartPolicy: Always
      volumes:
        - name: config
          secret:
            secretName: clair-config-secret
        - name: certs
          secret:
            secretName: quay-config-secret
            # Mount just the public certificate because we are using storage proxying.
            items:
              - key: ssl.cert
                path: quay-ssl.cert
