apiVersion: batch/v1
kind: Job
metadata:
  name: quay-postgres-migrate
spec:
  template:
    metadata:
      name: quay-postgres-migrate
    spec:
      restartPolicy: Never
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            # FIXME(alecmerdler): Change PVC name
            claimName: quay-database
      containers:
        - name: quay-postgres-migrate
          image: postgres:latest
          env:
            - name: DB_URI
              value: postgresql://old-quay-database:old-quay-database@old-quay-postgresql/old-quay-database
          command:
            - "pg_dump" 
            - "$(DB_URI)" 
            - "--format"
            - "c" 
            - "--file" 
            - "/var/lib/postgresql/data/dump.sql"
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
