{{- if .Values.openshift -}}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "quay-operator.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "quay-operator.fullname" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "quay-operator.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end -}}