# permissions for end users to view quayecosystems.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: quayecosystem-viewer-role
rules:
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - quayecosystems
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - quayecosystems/status
  verbs:
  - get
