# permissions for end users to edit quayecosystems.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: quayecosystem-editor-role
rules:
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - quayecosystems
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - quayecosystems/status
  verbs:
  - get
