apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: quay-operator
spec:
  sourceType: grpc
  image: quay.io/alecmerdler/quay-operator-catalog@sha256:b0435a516fab6b5035aae37f2e6e5d18f89e78e3b68ff97d5b3215983dffe5d2
